vmware-tanzu-labs/yaml-overlay-tool

.gitignore, README.md, yot
=> Logging mechanism

.github/workflows/lint.yaml
Adding pylint as a github action to lint python code as it gets pushed
=> Add Python Linter Github Action

.pylintrc, yot
=> python-lint-fixes

.github/workflows/dco.yml, .github/workflows/license.yml, .github/workflows/lint.yaml, .gitignore, .licenserc.json, .pylintrc, README.md, examples/static/instructions.yaml, examples/templated/instructions.yaml, yot
@ahuffman we can adjust the config as needed via the .licenserc.json file 
Closes #16
=> Add license check

docs/sections/qualifiers.md, docs/sections/useCasesForKubernetes.md, examples/kubernetes/removeAnnotationsWithConditions.yaml, examples/static/instructions.yaml, examples/static/test.yaml, internal/instructions/testdata/instructions.yaml, internal/instructions/testdata/test.yaml, internal/overlays/documentquery.go, internal/overlays/documentquery_internal_test.go
=> refactor(documentQuery): change key to query for better ux

docs/sections/outputDirStructure.md
=> docs: update docs to reflect new output paths

docs/sections/orderOfOperations.md
=> docs: fix output directory paths

docs/sections/instructionsFile.md, examples/kubernetes/addLabels.yaml, examples/kubernetes/formatLabelKey.yaml, examples/kubernetes/insertComments.yaml, examples/kubernetes/privateContainerRegistry.yaml, examples/kubernetes/removeAnnotations.yaml, examples/kubernetes/removeAnnotationsWithConditions.yaml, examples/kubernetes/replaceLabelKey.yaml, examples/static/arrayTest.yaml, examples/static/instructions.yaml, examples/static/test.yaml, examples/static/testMerge.yaml, internal/instructions/execute_test.go, internal/instructions/instructions.go, internal/instructions/testdata/arrayTest.yaml, internal/instructions/testdata/instructions.yaml, internal/instructions/testdata/testInstructions.yaml, internal/instructions/testdata/testMerge.yaml, internal/instructions/yamlfile.go
=> refactor(instructions)!: yaml file paths are now relative to instructions file

README.md, docs/sections/outputDirStructure.md
=> docs: update roadmap to templates in v0.3.0

internal/actions/delete.go, internal/instructions/yamlfile.go
using a query of $ you are now able to delete an entire document
and prevent it from being included in the output
closes #55
=> feat(delete): allow entire document to be deleted

internal/instructions/yamlfile.go
merge duplicate yaml file entries, appending overlays and
documents found to the original entry. Final output will use the last
non nil outputPath found
closes #53
=> feat(yamlFile): merge duplicate entries found in yamlFiles

.goreleaser.yml, Dockerfile
add docker file image and release configuration
=> feat: add docker file

go.mod, go.sum
jsonPath filters can be used on all nodes not just arrays
Closes #61
=> feat(query): allow filter expressions on all nodes

internal/instructions/config.go, internal/instructions/execute.go, internal/instructions/yamlfile.go, internal/overlays/query.go
currently there is a bug where if a document is deleted any overlay attempting to query that document later will result in a panic
=> Fix delete document bug

docs/sections/setup.md
=> docs(setup): add wget and docker instructions

.goreleaser.yml, go.sum, scripts/completions.sh
=> feat: release yot homebrew and linux packages

internal/commands/docs.go
Signed-off-by: Andrew J. Huffman <ahuffman@vmware.com>
=> docs: update help messaging

docs/sections/comments.md, docs/sections/formatMarkers.md, docs/sections/instructionsFile.md, docs/sections/qualifiers.md, docs/sections/setup.md, docs/sections/useCasesForKubernetes.md
Co-authored-by: lizz7000
Signed-off-by: Andrew J. Huffman <ahuffman@vmware.com>
=> docs: enhance docs for v0.4.0

.vscode/launch.json, internal/actions/action.go, internal/commands/completion.go, internal/commands/docs.go, internal/commands/flags.go, internal/commands/root.go, internal/commands/root_test.go, internal/instructions/config.go, internal/instructions/execute.go, internal/instructions/instructions.go, internal/instructions/yamlfile.go, internal/overlays/query.go
=> feat: add ability to apply overlays via stdin

internal/commands/flags.go, internal/instructions/config.go, internal/instructions/instructions.go
=> fix(path): allow path to be a directory, correct output name

internal/instructions/config.go, internal/instructions/yamlfile.go
=> fix: read all yaml files given in path parameter

docs/sections/formatMarkers.md, examples/kubernetes/formatStringReplace.yaml
Signed-off-by: Andrew J. Huffman <ahuffman@vmware.com>
=> docs(format markers): updates to examples for v0.6.0

.github/workflows/release.yml, .goreleaser.yml
Signed-off-by: Andrew J. Huffman <ahuffman@vmware.com>
Closes #69
=> feat: add GPG signed checksums
